create table users
(
    user_id    bigint generated by default as identity
        primary key,
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    password   varchar(255),
    role       smallint
        constraint users_role_check
            check ((role >= 0) AND (role <= 2))
);

create table parent
(
    user_id bigint not null
        primary key
        constraint fkq8m6xbjpeo258rd85jvrb36cs
            references users
);

create table student
(
    user_id        bigint not null
        primary key
        constraint fkk0thg920a3xk3v59yjbsatw1l
            references users,
    parent_user_id bigint
        constraint fk4sa3aikdwkxa64ol9a238t2p4
            references parent
);

create table teacher
(
    subject varchar(255),
    user_id bigint not null
        primary key
        constraint fkcp1vpkh4bh0qux9vtvs0fkwrn
            references users
);

create table grades
(
    id         bigint generated by default as identity
        primary key,
    value      double precision,
    student_id bigint
        constraint fkfs17qemf5ndxw3b7epeeep4ey
            references student,
    teacher_id bigint
        constraint fk566crflu2e9piq4ok465rvotr
            references teacher
);
